config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#welcome'
  get 'pages/main' => 'pages#main'
  get 'about' => 'about#about'
  get 'contact' => 'contact#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def about
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def contact
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def welcome
    end

    def main
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/about/about.html.erb
<div class="main">
    <div class="row">
        <div class="col-md-5 col-sm-5">
            <img src="https://s3-us-west-2.amazonaws.com/edudebt.info/test-portfolio/20180201_111404.jpg" />
        </div>
        <div class="desc offset-md-1 col-md-6 col-sm-7">
            <p>Greetings, fellow humans. My name is Brian Kim, senior in high school, and this is the portfolio I made instead of paying attention in class.</p>
            <p>My main talents are web development, fiction writing and short stories in particular, philosophical musings, and literary analysis.</p>
            <p>In my spare time, I'm probably reading something, watching TedEd videos, and ingesting liquids. <span style="color: white">not</span> </p>
        </div>
    </div>
    <div class="row">
        <div class="desc col-md-6 col-sm-7">
            <p>I'm currently learning to write in Python, C++, and Ruby. Java, but unwillingly. I'm also trying to become a full stack developer with Ruby on Rails.</p>
            <p>If you're at all inclined to hire me, I work ridiculous hours and only require occasional rest, feeding, and watering.</p>
            <p>Payment would be nice, obviously. I accept pretty much anything that I can use to pay for a Spotify Premium. Amazon gift cards work, too.</p>
        </div>
        <div class="offset-md-1 col-md-5 col-sm-5">
            <img src="https://s3-us-west-2.amazonaws.com/edudebt.info/test-portfolio/IMG_6291.JPG" />
        </div>
    </div>
</div>

app/views/contact/contact.html.erb
<div class="main">
    <div class="row">
        <div class="offset-md-2 col-md-8 offset-sm-1 col-sm-10">Contact me through any of these methods!</div>
    </div>
    <div class="row">
        <div class="contact offset-md-0 col-md-4 offset-sm-2 col-sm-10"><%= link_to "Email", "mailto:bsk945@gmail.com" %></div>
        <div class="col-md-8"></div>
    </div>
    <div class="row">
        <div class="contact offset-md-4 col-md-4 col-sm-10"><%= link_to "Facebook", "https://www.facebook.com/profile.php?id=100012117677484" %></div>
        <div class="col-md-4"></div>
        <!-- <div class="offset-md-2 col-md-2"><img class="logo-img" src="https://s3-us-west-2.amazonaws.com/edudebt.info/test-portfolio/600px-Facebook_logo_(square).png" /></div> -->
    </div>
    <div class="row">
        <div class="contact offset-md-8 col-md-4 offset-sm-2 col-sm-10"><%= link_to "Github", "https://github.com/QuantumScrewdriver" %></div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    
    <%= stylesheet_link_tag    'skippr', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="nav">
      <ul>
        <li><%= link_to "My Work", pages_main_path %></li>
        <li><%= link_to "Blog", "https://edudebt.info/" %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Me", contact_path %>
      </ul>
    </div>
    <%= yield %>
    <div class="footer">
      <a><img src="https://s3-us-west-2.amazonaws.com/edudebt.info/test-portfolio/instagram-social-network-logo-of-photo-camera.png" /></a>
      <a><img src="https://s3-us-west-2.amazonaws.com/edudebt.info/test-portfolio/facebook-logo.png" /></a>
      <a><img src="https://s3-us-west-2.amazonaws.com/edudebt.info/test-portfolio/linkedin-sign.png" /></a>
      <a><img src="https://s3-us-west-2.amazonaws.com/edudebt.info/test-portfolio/twitter-logo.png" /></a>
    </div>
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= yield :extra_links %>
  </body>
</html>

app/views/pages/main.html.erb
<div id="container">
    <div id="theTarget" class="slider-container">
        <div>
            <img src="https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-507187547455/resources/portfolio-images/BassMusic.png" />
        </div>
        <div>
            <img src="https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-507187547455/resources/portfolio-images/Bookmarks.png" />
        </div>
        <div>
            <img src="https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-507187547455/resources/portfolio-images/Threadly.png" />
        </div>
    </div>    
</div>

<% content_for :extra_links do %>
    <%= javascript_include_tag 'skippr', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<% end %>

app/views/pages/welcome.html.erb
<div class="header">
    <div class="container">
        <h1>Brian Kim</h1>
        <p>Unrelenting, brutally efficient, multifaceted, mature closet fascist</p>
    </div>
    <!--<div class="button-holder"><button>View my Work</button></div>-->
</div>